title: Gaming Security Experiments
description: A website to fnd the resources related to the experiments conducted on security and cheating in gaming environments.
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
